# Generated by Django 2.2.1 on 2019-05-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('questions', '0002_auto_20190512_1652'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answervote',
            unique_together={('answer', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='questionvote',
            unique_together={('question', 'user')},
        ),
    ]
