# Generated by Django 2.2.1 on 2019-05-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_department_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.CharField(max_length=200),
        ),
    ]
